# Observations file
#observations_file: "observations/one_fish_still.json"
#observations_file: "observations/two_fishes_still.json"
observations_file: "observations/three_fishes.json"
#observations_file: "observations/test_0.json"
#observations_file: "observations/test_1.json"
#observations_file: "observations/test_2.json"
#observations_file: "observations/test_3.json"

## Player type or nature. Possible values: "ai_minimax" or "human". Default: "ai_minimax"
player_type: "ai_minimax"

# Gameplay Speedup
gameplay_speedup: 10